In [5]:
import pandas  as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [6]:
data =  pd.read_csv("/content/BankChurners.csv")

In [7]:
data

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3   
1      818770008  Existing Customer            49      F                5   
2      713982108  Existing Customer            51      M                3   
3      769911858  Existing Customer            40      F                4   
4      709106358  Existing Customer            40      M                3   
...          ...                ...           ...    ...              ...   
10122  772366833  Existing Customer            50      M                2   
10123  710638233  Attrited Customer            41      M                2   
10124  716506083  Attrited Customer            44      F                1   
10125  717406983  Attrited Customer            30      M                2   
10126  714337233  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
3         High School        Unknown  Less than $40K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
...               ...            ...             ...           ...   
10122        Graduate         Single     $40K - $60K          Blue   
10123         Unknown       Divorced     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10125        Graduate        Unknown     $40K - $60K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777   
1                  44  ...        8256.0                  864   
2                  36  ...        3418.0                    0   
3                  34  ...        3313.0                 2517   
4                  21  ...        4716.0                    0   
...               ...  ...           ...                  ...   
10122              40  ...        4003.0                 1851   
10123              25  ...        4277.0                 2186   
10124              36  ...        5409.0                    0   
10125              36  ...        5281.0                    0   
10126              25  ...       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0                 0.535             8395              62   
10126           8427.0                 0.703            10294              61   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061   
1                    3.714                  0.105   
2                    2.333                  0.000   
3                    2.333                  0.760   
4                    2.500                  0.000   
...                    ...                    ...   
10122                0.857                  0.462   
10123                0.683                  0.511   
10124     

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype  
---  ------                                                                                                                              --------------  -----  
 0   CLIENTNUM                                                                                                                           10127 non-null  int64  
 1   Attrition_Flag                                                                                                                      10127 non-null  object 
 2   Customer_Age                                                                                                                        10127 non-null  int64  
 3   Gender                                                                           

In [9]:
data.isnull().sum()

CLIENTNUM                                                                                                                             0
Attrition_Flag                                                                                                                        0
Customer_Age                                                                                                                          0
Gender                                                                                                                                0
Dependent_count                                                                                                                       0
Education_Level                                                                                                                       0
Marital_Status                                                                                                                        0
Income_Category                                                                                                                       0
Card_Category                                                                                                                         0
Months_on_book                                                                                                                        0
Total_Relationship_Count                                                                                                              0
Months_Inactive_12_mon                                                                                                                0
Contacts_Count_12_mon                                                                                                                 0
Credit_Limit                                                                                                                          0
Total_Revolving_Bal                                                                                                                   0
Avg_Open_To_Buy                                                                                                                       0
Total_Amt_Chng_Q4_Q1                                                                                                                  0
Total_Trans_Amt                                                                                                                       0
Total_Trans_Ct                                                                                                                        0
Total_Ct_Chng_Q4_Q1                                                                                                                   0
Avg_Utilization_Ratio                                                                                                                 0
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1    0
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2    0
dtype: int64

In [10]:
data.Card_Category.unique()

array(['Blue', 'Gold', 'Silver', 'Platinum'], dtype=object)

In [11]:
data.shape

(10127, 23)

In [12]:
data.Months_Inactive_12_mon.unique()

array([1, 4, 2, 3, 6, 0, 5])

In [13]:
data.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

In [14]:
display(data['Total_Amt_Chng_Q4_Q1'])

0        1.335
1        1.541
2        2.594
3        1.405
4        2.175
         ...  
10122    0.703
10123    0.804
10124    0.819
10125    0.535
10126    0.703
Name: Total_Amt_Chng_Q4_Q1, Length: 10127, dtype: float64

In [15]:
print(data['Total_Amt_Chng_Q4_Q1'].values)

[1.335 1.541 2.594 ... 0.819 0.535 0.703]


In [13]:
print(list(data['Total_Ct_Chng_Q4_Q1']))

[1.625, 3.714, 2.333, 2.333, 2.5, 0.846, 0.722, 0.714, 1.182, 0.882, 0.68, 1.364, 3.25, 2.0, 0.611, 1.7, 0.929, 1.625, 1.143, 0.909, 0.929, 0.6, 1.571, 0.353, 0.75, 0.833, 1.3, 1.0, 1.571, 0.9, 2.571, 1.6, 1.667, 1.0, 0.714, 0.483, 1.176, 1.2, 0.556, 0.143, 0.474, 0.556, 1.2, 1.0, 0.917, 1.333, 0.588, 1.7, 0.8, 0.6, 1.143, 0.9, 1.923, 0.25, 0.364, 0.6, 0.6, 1.417, 1.083, 1.25, 0.833, 0.5, 1.154, 0.733, 0.917, 0.6, 0.667, 0.556, 2.4, 2.0, 1.05, 0.286, 0.4, 0.522, 1.182, 0.435, 1.875, 0.966, 0.353, 0.4, 1.412, 0.526, 0.714, 0.818, 2.0, 0.667, 0.722, 0.6, 1.8, 1.636, 1.333, 2.182, 0.619, 0.933, 1.222, 0.882, 0.304, 0.68, 0.727, 0.385, 1.0, 0.733, 0.5, 1.5, 0.789, 0.542, 1.1, 0.667, 1.095, 0.824, 0.391, 1.625, 0.346, 3.0, 1.056, 1.571, 1.118, 0.786, 1.0, 1.0, 0.625, 0.611, 1.533, 0.382, 0.355, 0.846, 0.364, 0.353, 1.417, 0.765, 0.778, 2.2, 1.545, 0.7, 1.0, 0.929, 0.733, 1.211, 1.231, 0.727, 0.8, 0.636, 1.5, 0.667, 1.0, 0.455, 2.875, 1.0, 1.308, 0.625, 0.467, 1.909, 0.571, 1.231, 1.364, 0.7

In [16]:
data

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3   
1      818770008  Existing Customer            49      F                5   
2      713982108  Existing Customer            51      M                3   
3      769911858  Existing Customer            40      F                4   
4      709106358  Existing Customer            40      M                3   
...          ...                ...           ...    ...              ...   
10122  772366833  Existing Customer            50      M                2   
10123  710638233  Attrited Customer            41      M                2   
10124  716506083  Attrited Customer            44      F                1   
10125  717406983  Attrited Customer            30      M                2   
10126  714337233  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
3         High School        Unknown  Less than $40K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
...               ...            ...             ...           ...   
10122        Graduate         Single     $40K - $60K          Blue   
10123         Unknown       Divorced     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10125        Graduate        Unknown     $40K - $60K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777   
1                  44  ...        8256.0                  864   
2                  36  ...        3418.0                    0   
3                  34  ...        3313.0                 2517   
4                  21  ...        4716.0                    0   
...               ...  ...           ...                  ...   
10122              40  ...        4003.0                 1851   
10123              25  ...        4277.0                 2186   
10124              36  ...        5409.0                    0   
10125              36  ...        5281.0                    0   
10126              25  ...       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0                 0.535             8395              62   
10126           8427.0                 0.703            10294              61   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061   
1                    3.714                  0.105   
2                    2.333                  0.000   
3                    2.333                  0.760   
4                    2.500                  0.000   
...                    ...                    ...   
10122                0.857                  0.462   
10123                0.683                  0.511   
10124     

In [15]:
data.drop('CLIENTNUM',axis=1,inplace=True)

In [17]:
data

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3   
1      818770008  Existing Customer            49      F                5   
2      713982108  Existing Customer            51      M                3   
3      769911858  Existing Customer            40      F                4   
4      709106358  Existing Customer            40      M                3   
...          ...                ...           ...    ...              ...   
10122  772366833  Existing Customer            50      M                2   
10123  710638233  Attrited Customer            41      M                2   
10124  716506083  Attrited Customer            44      F                1   
10125  717406983  Attrited Customer            30      M                2   
10126  714337233  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
3         High School        Unknown  Less than $40K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
...               ...            ...             ...           ...   
10122        Graduate         Single     $40K - $60K          Blue   
10123         Unknown       Divorced     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10125        Graduate        Unknown     $40K - $60K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777   
1                  44  ...        8256.0                  864   
2                  36  ...        3418.0                    0   
3                  34  ...        3313.0                 2517   
4                  21  ...        4716.0                    0   
...               ...  ...           ...                  ...   
10122              40  ...        4003.0                 1851   
10123              25  ...        4277.0                 2186   
10124              36  ...        5409.0                    0   
10125              36  ...        5281.0                    0   
10126              25  ...       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0                 0.535             8395              62   
10126           8427.0                 0.703            10294              61   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061   
1                    3.714                  0.105   
2                    2.333                  0.000   
3                    2.333                  0.760   
4                    2.500                  0.000   
...                    ...                    ...   
10122                0.857                  0.462   
10123                0.683                  0.511   
10124     

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in data.columns:
  if data[i].dtype == 'object'or data[i].dtype == 'bool':
    data[i] = le.fit_transform(data[i])

In [19]:
data

CLIENTNUM  Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0      768805383               1            45       1                3   
1      818770008               1            49       0                5   
2      713982108               1            51       1                3   
3      769911858               1            40       0                4   
4      709106358               1            40       1                3   
...          ...             ...           ...     ...              ...   
10122  772366833               1            50       1                2   
10123  710638233               0            41       1                2   
10124  716506083               0            44       0                1   
10125  717406983               0            30       1                2   
10126  714337233               0            43       0                2   

       Education_Level  Marital_Status  Income_Category  Card_Category  \
0                    3               1                2              0   
1                    2               2                4              0   
2                    2               1                3              0   
3                    3               3                4              0   
4                    5               1                2              0   
...                ...             ...              ...            ...   
10122                2               2                1              0   
10123                6               0                1              0   
10124                3               1                4              0   
10125                2               3                1              0   
10126                2               1                4              3   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777   
1                  44  ...        8256.0                  864   
2                  36  ...        3418.0                    0   
3                  34  ...        3313.0                 2517   
4                  21  ...        4716.0                    0   
...               ...  ...           ...                  ...   
10122              40  ...        4003.0                 1851   
10123              25  ...        4277.0                 2186   
10124              36  ...        5409.0                    0   
10125              36  ...        5281.0                    0   
10126              25  ...       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0                 0.535             8395              62   
10126           8427.0                 0.703            10294              61   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061   
1                    3.714                  0.105   
2                    2.333                  0.000   
3                    2.333                  0.760   
4                    2.500                  0.000   
...                    ...                    ...   
10122                0.857                  0.462   
10123                0.683             

In [21]:
x = data.drop('Attrition_Flag',axis=1)
y = data['Attrition_Flag']

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
x_train

CLIENTNUM  Customer_Age  Gender  Dependent_count  Education_Level  \
9066  713071383            54       0                1                6   
5814  714246333            58       0                4                3   
792   718206783            45       0                4                6   
1791  721096983            34       0                2                2   
5011  720028683            49       0                2                3   
...         ...           ...     ...              ...              ...   
5734  769053033            44       0                1                2   
5191  714406158            53       0                3                3   
5390  714140133            42       0                4                2   
860   720244983            40       1                3                6   
7270  827123883            53       1                4                3   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
9066               2                5              0              36   
5814               1                5              0              48   
792                2                4              1              36   
1791               2                4              0              36   
5011               1                1              0              39   
...              ...              ...            ...             ...   
5734               2                1              0              38   
5191               0                5              0              36   
5390               3                4              0              32   
860                2                1              0              28   
7270               2                2              0              49   

      Total_Relationship_Count  ...  Credit_Limit  Total_Revolving_Bal  \
9066                         1  ...        3723.0                 1728   
5814                         1  ...        5396.0                 1803   
792                          6  ...       15987.0                 1648   
1791                         4  ...        3625.0                 2517   
5011                         5  ...        2720.0                 1926   
...                        ...  ...           ...                  ...   
5734                         3  ...        4142.0                 2517   
5191                         4  ...        7939.0                    0   
5390                         3  ...        2314.0                 1547   
860                          4  ...        3563.0                 1707   
7270                         5  ...        3858.0                    0   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
9066           1995.0                 0.595             8554              99   
5814           3593.0                 0.493             2107              39   
792           14339.0                 0.732             1436              36   
1791           1108.0                 1.158             2616              46   
5011            794.0                 0.602             3806              61   
...               ...                   ...              ...             ...   
5734           1625.0                 0.809             2104              44   
5191           7939.0                 0.551             2269              42   
5390            767.0                 0.804             4678              74   
860            1856.0                 0.506             1482              42   
7270           3858.0                 0.670             4472              92   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
9066                0.678                  0.464   
5814                0.393                  0.334   
792                 1.250                  0.103   
1791                1.300                  0.694   
5011                0.794                  0.708   
...                   ...                    ...   
5734                0.833 

In [21]:
y_train

9066    1
5814    0
792     1
1791    1
5011    1
       ..
5734    0
5191    0
5390    1
860     1
7270    1
Name: Attrition_Flag, Length: 8101, dtype: int64

In [22]:
x_test

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
3781            48       0                3                5               2   
2922            59       1                1                5               2   
5070            37       0                2                2               0   
7246            47       1                3                1               0   
623             42       1                3                6               2   
...            ...     ...              ...              ...             ...   
1937            34       1                2                2               2   
4705            35       0                1                0               2   
8548            44       0                1                5               0   
1346            27       1                0                2               2   
8802            39       0                0                6               2   

      Income_Category  Card_Category  Months_on_book  \
3781                4              0              39   
2922                4              0              53   
5070                4              0              36   
7246                1              0              36   
623                 3              0              33   
...               ...            ...             ...   
1937                3              0              29   
4705                4              0              25   
8548                4              0              37   
1346                0              0              17   
8802                1              3              26   

      Total_Relationship_Count  Months_Inactive_12_mon  ...  Credit_Limit  \
3781                         4                       3  ...        2991.0   
2922                         5                       5  ...        2192.0   
5070                         4                       3  ...        1734.0   
7246                         4                       2  ...        4786.0   
623                          3                       3  ...        3714.0   
...                        ...                     ...  ...           ...   
1937                         3                       1  ...       13395.0   
4705                         2                       2  ...        2231.0   
8548                         1                       2  ...        5594.0   
1346                         6                       2  ...        8713.0   
8802                         1                       1  ...       22054.0   

      Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
3781                 1508           1483.0                 0.703   
2922                 1569            623.0                 0.706   
5070                  987            747.0                 0.879   
7246                 1516           3270.0                 0.940   
623                  2170           1544.0                 0.524   
...                   ...              ...                   ...   
1937                 1678          11717.0                 1.006   
4705                 1791            440.0                 0.820   
8548                 1235           4359.0                 0.549   
1346                 1354           7359.0                 0.558   
8802                 1146          20908.0                 0.842   

      Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
3781             3734              64                0.882   
2922             4010              79                0.717   
5070             4727              67                0.914   
7246             4973              74                0.850   
623              1454              35                0.522   
...               ...             ...                  ...   
1937             2650              69                0.865   
4705             2576              42                0.750   
8548             5220              75                0.829   
1346      

**# 3. Build a Logistic Regression classification model which will predict whether a customer is at risk to churn from the platform**

In [23]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [24]:
lr.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1])

In [25]:
lr.score(x_test,y_test)

0.9279368213228035

In [26]:
#First Row predict(manually)
lr.predict([[45, 1, 3, 3, 1, 2, 0, 39, 5, 1, 3, 12691, 777, 11914, 1.335, 1144, 42, 1.625, 0.061, 0.000093, 0.999910]])


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

**Build Naive Bayes model which will predict whether a customer is at risk to churn from the platform**

In [27]:
#2)Build Naive Bayes model which will predict whether a customer is at risk to churn from the platform
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
gb = GaussianNB()
mn = MultinomialNB()
bn = BernoulliNB()
gb.fit(x_train,y_train)



GaussianNB()

In [28]:
mn.fit(x_train,y_train)

MultinomialNB()

In [29]:
bn.fit(x_train,y_train)

BernoulliNB()

In [30]:
mn.score(x_test,y_test)

0.6604146100691016

In [31]:
bn.score(x_test,y_test)

0.7813425468904245

In [32]:
gb.score(x_test,y_test)

1.0

In [33]:
gb.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1])

In [34]:
gb.predict([[45, 1, 3, 3, 1, 2, 0, 39, 5, 1, 3, 12691, 777, 11914, 1.335, 1144, 42, 1.625, 0.061, 0.000093, 0.999910]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1])

# **Build a K-nearest classifier which will predict whether a customer is at risk to churn from the platform.**

In [35]:
#Build a K-nearest classifier which will predict whether a customer is at risk to churn from the platform.
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier( n_neighbors= 1820,metric = "minkowski")
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1820)

In [36]:
knn.score(x_test,y_test)

0.8385982230997039

In [37]:
knn.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1])

In [38]:
knn.predict([[45, 1, 3, 3, 1, 2, 0, 39, 5, 1, 3, 12691, 777, 11914, 1.335, 1144, 42, 1.625, 0.061, 0.000093, 0.999910]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

**6**. Find optimal parameters for the algorithm through GridSearchCV and build SVC
model which will predict whether a customer is at risk to churn from the platform.

In [24]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)

In [26]:
svc = SVC()
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# 5. GridSearchCV
grid_search = GridSearchCV(svc, param_grid, cv=5, verbose=1)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits


GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=1)

In [27]:
grid_search.score(x_test,y_test)

1.0

In [28]:
grid_search.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1])

# **7) Find optimal parameters for the algorithm through GridSearchCV and build a Decision tree which will predict whether a customer is at risk to churn from the platform**

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dt = DecisionTreeClassifier()
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10]}
grid_search = GridSearchCV(dt, param_grid, cv=5, verbose=1)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10]},
             verbose=1)

In [36]:
grid_search.score(x_test,y_test)

1.0

In [37]:
grid_search.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1])

# **8**. Find optimal parameters for the algorithm through RandomSearchCV and build a Random which will predict whether a customer is at risk to churn from the platform

In [39]:
from sklearn.metrics import classification_report
from scipy.stats import randint

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report
from scipy.stats import randint

rf = RandomForestClassifier()
param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': randint(3, 20),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 10),
    'bootstrap': [True, False]
}

# 4. RandomizedSearchCV
random_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=20,  # Number of combinations to try
    cv=5,
    verbose=1,
    n_jobs=-1,
    random_state=42
)

random_search.fit(x_train, y_train)

# 5. Best Parameters
print("Best Parameters:", random_search.best_params_)

# 6. Predict and evaluate
best_rf = random_search.best_estimator_
y_pred = best_rf.predict(x_test)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best Parameters: {'bootstrap': True, 'max_depth': 17, 'min_samples_leaf': 8, 'min_samples_split': 6, 'n_estimators': 70}


In [42]:
random_search.score(x_test,y_test)

1.0

In [43]:
random_search.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1])

In [46]:
from sklearn.metrics import classification_report,accuracy_score
p =classification_report(y_test, y_pred)
c =accuracy_score(y_test,y_pred)
print(p)
print(c)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       327
           1       1.00      1.00      1.00      1699

    accuracy                           1.00      2026
   macro avg       1.00      1.00      1.00      2026
weighted avg       1.00      1.00      1.00      2026

1.0
